name: SonarCloud and Update Fork

on:
  schedule:
    - cron: '0 0 * * *' 
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: dev

      - name: Configure Git
        run: |
          git config user.name "arthurmkrtchian"
          git config user.email "mkrtchian.arthur999@gmail.com"

      - name: Add remote upstream
        run: git remote add upstream https://github.com/GreenCity23/GreenCityUserMVPTemplate.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Temporarily stash changes of the files you want to exclude
        run: |
          git stash push "pom.xml" || echo "Stashed pom.xml"
          git stash push ".github/workflows/main.yml" || echo "Stashed main.yml"

      - name: Merge changes from the upstream dev branch
        run: git merge upstream/dev

      - name: Format code
        run: mvn formatter:format

      - name: Check for changes and commit
        run: |
          git add .
          if git diff --cached --exit-code; then
            echo "No changes detected after formatting. Skipping commit."
          else
            git commit -m "Apply code formatting"
            git push origin dev
          fi

      - name: Restore the stashed files
        run: |
          git stash list | grep -q 'stash@{0}' && git stash pop || echo "No stash to apply for main.yml"
          git stash list | grep -q 'stash@{0}' && git stash pop || echo "No stash to apply for pom.xml"

      - name: Commit and push changes
        run: |
          git add .
          git diff --cached --exit-code || git commit -m "Merge upstream changes, excluding my special files"
          git push origin dev || echo "No changes to push"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=greencity23-analytics_usermvptemplate -Dsonar.sources='src/main/java/greencity' -Dsonar.binaries=target/classes -Dsonar.dynamicAnalysis=reuseReports -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
